name: DrRob
favicon: null
layout_spectrum: 1
typography_spectrum: 0.91587
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000610'
    - '#3d464d'
    - '#71767c'
    - '#10a6c8'
    - '#d0e6eb'
  brandStrength: 0.4840796901844442
  lightness: 0.4251357102766633
  saturation: 0.44632683019153774
  rhythmicContrast: 0.7162318266928196
purpose: []
